-- usage: psql -v n=5000000 -v v=1000000 -f load.sql
\timing on
DROP TABLE IF EXISTS domains;
-- status: 0 discovered, 1 visiting, 2 visited, 3 failed
CREATE TABLE domains (
  id             bigint GENERATED BY DEFAULT AS IDENTITY,
  discovered_at  timestamptz NOT NULL DEFAULT now(),
  claimed_at     timestamptz,
  visited_at     timestamptz,
  status         smallint NOT NULL DEFAULT 0,
  rk             smallint NOT NULL DEFAULT (random()*32767)::int,  -- approach D random key
  http_status    smallint,
  content_length integer,
  name           text NOT NULL,
  title          text,
  lang           text,
  ip             inet,
  server         text,
  redirect_to    text,
  error          text
);
INSERT INTO domains (id, discovered_at, claimed_at, visited_at, status, rk, http_status, content_length, name, title, lang, ip, server)
SELECT i,
       ts,
       CASE WHEN vis THEN ts + interval '1 day' END,
       CASE WHEN vis THEN ts + interval '1 day' END,
       CASE WHEN NOT vis THEN 0 WHEN i % 33 = 0 THEN 3 ELSE 2 END,
       (random()*32767)::int,
       CASE WHEN vis THEN 200 END,
       CASE WHEN vis THEN (random()*500000)::int END,
       substr(md5(i::text),1,8) || '-' || i || '.example',
       CASE WHEN vis THEN 'Welcome to site number ' || i || ' - home page' END,
       CASE WHEN vis THEN 'en' END,
       CASE WHEN vis THEN ('10.' || (i>>16 & 255) || '.' || (i>>8 & 255) || '.' || (i & 255))::inet END,
       CASE WHEN vis THEN 'nginx' END
FROM (
  SELECT i,
         timestamptz '2026-01-01' + (i/13) * interval '2 seconds' + (i%13) * interval '1 millisecond' AS ts,
         (i <= :v AND NOT (i > :v - 20000 AND random() < 0.3)) AS vis
  FROM generate_series(1, :n) i
) s;
SELECT setval(pg_get_serial_sequence('domains','id'), :n);
ALTER TABLE domains ADD PRIMARY KEY (id);
CREATE UNIQUE INDEX domains_name_key ON domains (name);
CREATE INDEX domains_frontier ON domains (discovered_at, id) WHERE status = 0;       -- approach A/B/C
CREATE INDEX domains_frontier_rk ON domains ((id >> 13), rk) WHERE status = 0;      -- approach D
VACUUM (FREEZE, ANALYZE) domains;
SELECT pg_size_pretty(pg_relation_size('domains')) heap,
       pg_relation_size('domains')/ (SELECT count(*) FROM domains) AS heap_bytes_per_row,
       pg_size_pretty(pg_indexes_size('domains')) all_idx;
SELECT indexrelname, pg_size_pretty(pg_relation_size(indexrelid)) FROM pg_stat_user_indexes WHERE relname='domains';
SELECT status, count(*) FROM domains GROUP BY 1 ORDER BY 1;
